# -*- coding: utf-8 -*-
"""Untitled49.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iQTiP8D51GXE-73Oi25kNp-ZiG_vQ5yc
"""

from scipy.stats import pearsonr
import numpy as np

a = np.random.normal(size=10)
b = np.random.normal(size=10)

b

from scipy.stats import spearmanr

pearsonr(a,b)

spearmanr(a,b)

from scipy.stats import kendalltau

kendalltau(a,b)



"""# Credit card Default prediction EDA"""

import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go
from plotly.subplots import make_subplots
pd.set_option('display.max_columns', 300) #Setting column display limit
plt.style.use('ggplot') #Applying style to graphs

df1 = pd.read_csv(r"/content/application_data.csv")

"""df1 -> Current application Data set
  
"""

df1.head()

df1.shape

df1.info(verbose=True)

df1.describe()

(df1.isnull().sum()/len(df1)*100).sort_values(ascending = False).head(50)

null_col = df1.isnull().sum().sort_values(ascending = False)
null_col = null_col[null_col.values >(0.35*len(df1))]


#Plotting Bar Graph for null values greater than 35%

plt.figure(figsize=(20,4))
null_col.plot(kind='bar', color="#4CB391")
plt.title('List of Columns & null counts where null values are more than 35%')

plt.xlabel("Null Columns",fontdict={"fontsize":12,"fontweight":5})                  #Setting X-label and Y-label
plt.ylabel("Count of null values",fontdict={"fontsize":12,"fontweight":5})
plt.show()

len(null_col)

label = list(null_col.index.values) #Making list of column names having null values greater than 35%
df1.drop(labels = label,axis=1,inplace = True) #Droping those columns
df1.shape

null = (df1.isnull().sum()/len(df1)*100).sort_values(ascending = False).head(50)
null.head(30)

df1.AMT_REQ_CREDIT_BUREAU_YEAR.fillna(df1.AMT_REQ_CREDIT_BUREAU_YEAR.mode()[0],inplace = True) #AMT_REQ_CREDIT_BUREAU_YEAR

df1.AMT_REQ_CREDIT_BUREAU_MON.fillna(df1.AMT_REQ_CREDIT_BUREAU_MON.mode()[0],inplace = True)   #AMT_REQ_CREDIT_BUREAU_MON

df1.AMT_REQ_CREDIT_BUREAU_WEEK.fillna(df1.AMT_REQ_CREDIT_BUREAU_WEEK.mode()[0],inplace = True) #AMT_REQ_CREDIT_BUREAU_WEEK

df1.AMT_REQ_CREDIT_BUREAU_DAY.fillna(df1.AMT_REQ_CREDIT_BUREAU_DAY.mode()[0],inplace = True)   #AMT_REQ_CREDIT_BUREAU_DAY

df1.AMT_REQ_CREDIT_BUREAU_HOUR.fillna(df1.AMT_REQ_CREDIT_BUREAU_HOUR.mode()[0],inplace = True) #AMT_REQ_CREDIT_BUREAU_HOUR

df1.AMT_REQ_CREDIT_BUREAU_QRT.fillna(df1.AMT_REQ_CREDIT_BUREAU_QRT.mode()[0],inplace = True)   #AMT_REQ_CREDIT_BUREAU_QRT

df1.NAME_TYPE_SUITE.fillna(df1.NAME_TYPE_SUITE.mode()[0],inplace = True) #NAME_TYPE_SUITE

df1.OBS_30_CNT_SOCIAL_CIRCLE.fillna( df1.OBS_30_CNT_SOCIAL_CIRCLE.mode()[0],inplace = True) #OBS_30_CNT_SOCIAL_CIRCLE

df1.DEF_30_CNT_SOCIAL_CIRCLE.fillna( df1.DEF_30_CNT_SOCIAL_CIRCLE.mode()[0],inplace = True) #DEF_30_CNT_SOCIAL_CIRCLE

df1.OBS_60_CNT_SOCIAL_CIRCLE.fillna( df1.OBS_60_CNT_SOCIAL_CIRCLE.mode()[0],inplace = True) #OBS_60_CNT_SOCIAL_CIRCLE

df1.DEF_60_CNT_SOCIAL_CIRCLE.fillna( df1.DEF_60_CNT_SOCIAL_CIRCLE.mode()[0],inplace = True) #DEF_60_CNT_SOCIAL_CIRCLE

df1.CNT_FAM_MEMBERS.fillna(df1.CNT_FAM_MEMBERS.mode() , inplace = True) #CNT_FAM_MEMBERS

df1.DAYS_LAST_PHONE_CHANGE.fillna(df1.DAYS_LAST_PHONE_CHANGE.mode()[0],inplace = True) #DAYS_LAST_PHONE_CHANGE

df1.EXT_SOURCE_2.fillna(df1.EXT_SOURCE_2.median() , inplace = True) #EXT_SOURCE_2

df1.EXT_SOURCE_3.fillna(df1.EXT_SOURCE_3.median() , inplace = True) #EXT_SOURCE_3

(df1.isnull().sum()/len(df1)*100).sort_values(ascending=False)

df1[["DAYS_BIRTH","DAYS_EMPLOYED","DAYS_REGISTRATION","DAYS_ID_PUBLISH","DAYS_LAST_PHONE_CHANGE"]]

day_cols = [i for i in df1 if i.startswith('DAYS')]
day_cols

df1[day_cols]= abs(df1[day_cols])
print(df1['DAYS_BIRTH'].unique())
print(df1['DAYS_EMPLOYED'].unique())
print(df1['DAYS_REGISTRATION'].unique())
print(df1['DAYS_ID_PUBLISH'].unique())
print(df1['DAYS_LAST_PHONE_CHANGE'].unique())

df1["FLAG_OWN_CAR"].value_counts()

df1["CODE_GENDER"].value_counts()

df1['FLAG_OWN_CAR'] = np.where(df1['FLAG_OWN_CAR']=='Y', 1 , 0)
df1['FLAG_OWN_REALTY'] = np.where(df1['FLAG_OWN_REALTY']=='Y', 1 , 0)

# Occupation = ["Farmer","Farmeer","Faarmer","IT Professional","Manager", "Clerk","Teacher","Business"] -> C

df1[['FLAG_OWN_CAR','FLAG_OWN_REALTY']].head()

df1.CODE_GENDER.value_counts()
df1.loc[df1.CODE_GENDER == 'XNA','CODE_GENDER'] = 'F'
df1.CODE_GENDER.value_counts()

df1.ORGANIZATION_TYPE.value_counts().head()

df1[['ORGANIZATION_TYPE','NAME_INCOME_TYPE']].head(30)

df1.NAME_INCOME_TYPE.value_counts()    #Check the counts for each in NAME_INCOME_TYPE

df1['ORGANIZATION_TYPE'] = df1['ORGANIZATION_TYPE'].replace('XNA', 'Pensioner')
df1['OCCUPATION_TYPE'].fillna('Pensioner' , inplace = True)

df1['AMT_INCOME_TYPE'] = pd.qcut(df1.AMT_INCOME_TOTAL, q=[0, 0.2, 0.5, 0.8, 0.95, 1], labels=['VERY_LOW', 'LOW', "MEDIUM", 'HIGH', 'VERY_HIGH'])
df1['AMT_INCOME_TYPE'].head(11)

df1['AMT_CREDIT_TYPE'] = pd.qcut(df1.AMT_CREDIT, q=[0, 0.2, 0.5, 0.8, 0.95, 1], labels=['VERY_LOW', 'LOW', "MEDIUM", 'HIGH', 'VERY_HIGH'])
df1['AMT_CREDIT_TYPE'].head(11)

df1['DAYS_BIRTH']= (df1['DAYS_BIRTH']/365).astype(int)    # Converting
df1['DAYS_BIRTH'].unique()
df1['AGE_GROUP']=pd.cut(df1['DAYS_BIRTH'],
                         bins=[19,25,35,60,100], labels=['Very_Young','Young', 'Middle_Age', 'Senior_Citizen'])   #Binning

df1[['DAYS_BIRTH','AGE_GROUP']].head()

df1.info()

unwanted=['FLAG_MOBIL', 'FLAG_EMP_PHONE', 'FLAG_WORK_PHONE', 'FLAG_CONT_MOBILE',
       'FLAG_PHONE', 'FLAG_EMAIL','REGION_RATING_CLIENT','REGION_RATING_CLIENT_W_CITY','FLAG_EMAIL', 'REGION_RATING_CLIENT',
       'REGION_RATING_CLIENT_W_CITY', 'FLAG_DOCUMENT_2', 'FLAG_DOCUMENT_3','FLAG_DOCUMENT_4', 'FLAG_DOCUMENT_5', 'FLAG_DOCUMENT_6',
       'FLAG_DOCUMENT_7', 'FLAG_DOCUMENT_8', 'FLAG_DOCUMENT_9','FLAG_DOCUMENT_10', 'FLAG_DOCUMENT_11', 'FLAG_DOCUMENT_12',
       'FLAG_DOCUMENT_13', 'FLAG_DOCUMENT_14', 'FLAG_DOCUMENT_15','FLAG_DOCUMENT_16', 'FLAG_DOCUMENT_17', 'FLAG_DOCUMENT_18',
       'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20', 'FLAG_DOCUMENT_21']

df1.drop(labels=unwanted,axis=1,inplace=True)

numerical_col = df1.select_dtypes(include='number').columns
len(numerical_col)

fig , axes = plt.subplots(nrows=3, ncols=1, constrained_layout=True)                 # Plot Configuration
fig.subplots_adjust(left= 0, bottom=0, right=3, top=12, wspace=0.09, hspace=0.3)


for ax, column in zip(axes.flatten(),numerical_col):        #Using For loop

    sns.boxplot(df1[column],ax=ax)   #Ploting

count1 = 0
count0 = 0
for i in df1['TARGET'].values:
    if i == 1:
        count1 += 1
    else:
        count0 += 1

count1 = (count1/len(df1['TARGET']))*100
count0 = (count0/len(df1['TARGET']))*100

x = ['Defaulted Population(TARGET=1)','Non-Defauted Population(TARGET=0)']
y = [count1, count0]

explode = (0.1, 0)  # only "explode" the 1st slice

fig1, ax1 = plt.subplots()
ax1.pie(y, explode=explode, labels=x, autopct='%1.1f%%',
        shadow=True, startangle=110)
ax1.axis('equal')  # Equal aspect ratio ensures that pie is drawn as a circle.
plt.title('Data imbalance',fontsize=25)
plt.show()

# Separate the data based on the TARGET variable
Target0 = df1[df1['TARGET'] == 0]  # Non-defaulters (no payment difficulties)
Target1 = df1[df1['TARGET'] == 1]  # Defaulters (payment difficulties)

# Optional: Check the shapes to verify the split
print(f"Target 0 shape: {Target0.shape}")
print(f"Target 1 shape: {Target1.shape}")
print(f"\nTarget 0 percentage: {(len(Target0)/len(df1))*100:.2f}%")
print(f"Target 1 percentage: {(len(Target1)/len(df1))*100:.2f}%")

plt.figure(figsize=(15,8))
plt.subplot(121)
sns.countplot(x='TARGET',hue='CODE_GENDER',data=Target0, palette = 'Set2')
plt.title("Gender Distribution in Target0")
plt.subplot(122)
sns.countplot(x='TARGET',hue='CODE_GENDER',data=Target1, palette = 'Set2')
plt.title("Gender Distribution in Target1")

plt.show()

plt.figure(figsize=(40,5))
plt.rcParams["axes.labelsize"] = 80
plt.rcParams['axes.titlesize'] = 80                                                           # Plot Configuration
plt.rcParams['axes.titlepad'] = 50
fig, axes = plt.subplots(nrows=1,ncols=2)
sns.set_context('talk')
fig.subplots_adjust(left= 0.09,bottom=1,right=3,top= 12,wspace=0.5,hspace=0.3)


plt.subplot(121)
plt.xscale('log')                                                                             # For Target0
sns.countplot(data=Target0,y='ORGANIZATION_TYPE',
              order=df1['ORGANIZATION_TYPE'].value_counts().index,palette='Set3',hue = 'TARGET')
plt.title("ORGANIZATION_TYPE Vs Target 0")



plt.subplot(122)
plt.xscale('log')                                                                              # For Target1
sns.countplot(data=Target1,y='ORGANIZATION_TYPE',
              order=df1['ORGANIZATION_TYPE'].value_counts().index,palette='Set1',hue = 'TARGET')
plt.title("ORGANIZATION_TYPE Vs Target 1")



plt.show();

def categorical_plot(var):
    plt.figure(figsize=(40,20))

    plt.rcParams['axes.labelpad'] = 50
    plt.subplot(1, 2, 1)
    sns.countplot(var, data=Target0, palette = 'Set3', hue='TARGET')
    plt.xlabel(var, fontsize= 30, fontweight="bold")                                                         #Target 0
    plt.ylabel('Non Payment Difficulties', fontsize= 30, fontweight="bold")
    plt.xticks(rotation=90, fontsize=30)
    plt.yticks(rotation=360, fontsize=30)


    plt.rcParams['axes.labelpad'] = 50
    plt.subplot(1, 2, 2)
    sns.countplot(var, data=Target1, palette = 'Set1', hue='TARGET')                                           # Target 1
    plt.xlabel(var, fontsize= 30, fontweight="bold")
    plt.ylabel('Payments Difficulties', fontsize= 30, fontweight="bold")
    plt.xticks(rotation=90, fontsize=30)
    plt.yticks(rotation=360, fontsize=30)
    plt.show()

categorical_col = list(df1.select_dtypes(include= 'category').columns)


# Removing 'ORGANIZATION_TYPE','CODE_GENDER','AGE_GROUP' because we have already taken up the isights from  above plots

categorical_col.remove('ORGANIZATION_TYPE')
categorical_col.remove('CODE_GENDER')
categorical_col.remove('AGE_GROUP')

categorical_col #Checking after removing columns





import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, roc_auc_score, roc_curve
import warnings
warnings.filterwarnings('ignore')

# Set style for better visualizations
sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (12, 6)

print("="*80)
print("EXPLORATORY DATA ANALYSIS (EDA) AND CLASSIFICATION")
print("Dataset: Wine Quality (UCI Machine Learning Repository)")
print("="*80)

# ============================================================================
# 1. DATA LOADING
# ============================================================================
print("\n[1] LOADING DATA...")
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"
df = pd.read_csv(url, sep=';')

print(f"\nDataset shape: {df.shape}")
print(f"Features: {df.shape[1]-1}, Samples: {df.shape[0]}")

# ============================================================================
# 2. BASIC DATA EXPLORATION
# ============================================================================
print("\n" + "="*80)
print("[2] BASIC DATA EXPLORATION")
print("="*80)

print("\nFirst 5 rows:")
print(df.head())

print("\nDataset Info:")
print(df.info())

print("\nMissing Values:")
print(df.isnull().sum())

print("\nBasic Statistics:")
print(df.describe())

# ============================================================================
# 3. UNIVARIATE ANALYSIS
# ============================================================================
print("\n" + "="*80)
print("[3] UNIVARIATE ANALYSIS")
print("="*80)

# Create binary target for classification (quality >= 6 is "good")
df['quality_binary'] = (df['quality'] >= 6).astype(int)
print(f"\nTarget Distribution (Good Wine: quality >= 6):")
print(df['quality_binary'].value_counts())
print(f"Percentage of Good Wine: {df['quality_binary'].mean()*100:.2f}%")

# Numerical features
numerical_features = df.columns[:-2]  # Exclude 'quality' and 'quality_binary'

# Distribution plots
fig, axes = plt.subplots(4, 3, figsize=(15, 12))
axes = axes.ravel()

for idx, col in enumerate(numerical_features):
    axes[idx].hist(df[col], bins=30, edgecolor='black', alpha=0.7)
    axes[idx].set_title(f'Distribution of {col}')
    axes[idx].set_xlabel(col)
    axes[idx].set_ylabel('Frequency')

    # Add statistics
    mean_val = df[col].mean()
    median_val = df[col].median()
    axes[idx].axvline(mean_val, color='r', linestyle='--', label=f'Mean: {mean_val:.2f}')
    axes[idx].axvline(median_val, color='g', linestyle='--', label=f'Median: {median_val:.2f}')
    axes[idx].legend(fontsize=8)

plt.tight_layout()
plt.savefig('univariate_analysis.png', dpi=300, bbox_inches='tight')
print("\n✓ Univariate distribution plots saved as 'univariate_analysis.png'")

# Skewness and Kurtosis
print("\nSkewness and Kurtosis:")
skew_kurt = pd.DataFrame({
    'Feature': numerical_features,
    'Skewness': [df[col].skew() for col in numerical_features],
    'Kurtosis': [df[col].kurtosis() for col in numerical_features]
})
print(skew_kurt)

# ============================================================================
# 4. BIVARIATE ANALYSIS
# ============================================================================
print("\n" + "="*80)
print("[4] BIVARIATE ANALYSIS")
print("="*80)

# Correlation with target
print("\nCorrelation with Target (quality_binary):")
correlations = df[numerical_features].corrwith(df['quality_binary']).sort_values(ascending=False)
print(correlations)

# Scatter plots for top correlated features
top_features = correlations.abs().sort_values(ascending=False).head(4).index

fig, axes = plt.subplots(2, 2, figsize=(14, 10))
axes = axes.ravel()

for idx, feature in enumerate(top_features):
    axes[idx].scatter(df[feature], df['quality'], alpha=0.5)
    axes[idx].set_xlabel(feature)
    axes[idx].set_ylabel('Quality Score')
    axes[idx].set_title(f'{feature} vs Quality (corr: {correlations[feature]:.3f})')

    # Add regression line
    z = np.polyfit(df[feature], df['quality'], 1)
    p = np.poly1d(z)
    axes[idx].plot(df[feature], p(df[feature]), "r--", alpha=0.8)

plt.tight_layout()
plt.savefig('bivariate_analysis.png', dpi=300, bbox_inches='tight')
print("\n✓ Bivariate scatter plots saved as 'bivariate_analysis.png'")

# Box plots by quality category
fig, axes = plt.subplots(2, 2, figsize=(14, 10))
axes = axes.ravel()

for idx, feature in enumerate(top_features):
    df.boxplot(column=feature, by='quality_binary', ax=axes[idx])
    axes[idx].set_title(f'{feature} by Wine Quality')
    axes[idx].set_xlabel('Quality (0=Poor, 1=Good)')
    axes[idx].set_ylabel(feature)

plt.suptitle('')
plt.tight_layout()
plt.savefig('boxplot_bivariate.png', dpi=300, bbox_inches='tight')
print("✓ Box plots saved as 'boxplot_bivariate.png'")

# ============================================================================
# 5. CORRELATION ANALYSIS
# ============================================================================
print("\n" + "="*80)
print("[5] CORRELATION ANALYSIS")
print("="*80)

# Correlation matrix
correlation_matrix = df[numerical_features].corr()
print("\nCorrelation Matrix:")
print(correlation_matrix)

# Heatmap
plt.figure(figsize=(12, 10))
sns.heatmap(correlation_matrix, annot=True, fmt='.2f', cmap='coolwarm',
            center=0, square=True, linewidths=1)
plt.title('Correlation Heatmap of Wine Features')
plt.tight_layout()
plt.savefig('correlation_heatmap.png', dpi=300, bbox_inches='tight')
print("\n✓ Correlation heatmap saved as 'correlation_heatmap.png'")

# Highly correlated pairs
print("\nHighly Correlated Feature Pairs (|r| > 0.7):")
high_corr = []
for i in range(len(correlation_matrix.columns)):
    for j in range(i+1, len(correlation_matrix.columns)):
        if abs(correlation_matrix.iloc[i, j]) > 0.7:
            high_corr.append([correlation_matrix.columns[i],
                            correlation_matrix.columns[j],
                            correlation_matrix.iloc[i, j]])
if high_corr:
    high_corr_df = pd.DataFrame(high_corr, columns=['Feature 1', 'Feature 2', 'Correlation'])
    print(high_corr_df)
else:
    print("No feature pairs with correlation > 0.7")

# ============================================================================
# 6. COVARIANCE ANALYSIS
# ============================================================================
print("\n" + "="*80)
print("[6] COVARIANCE ANALYSIS")
print("="*80)

# Covariance matrix
covariance_matrix = df[numerical_features].cov()
print("\nCovariance Matrix:")
print(covariance_matrix)

# Visualize covariance
plt.figure(figsize=(12, 10))
sns.heatmap(covariance_matrix, annot=True, fmt='.2f', cmap='viridis',
            square=True, linewidths=1)
plt.title('Covariance Matrix of Wine Features')
plt.tight_layout()
plt.savefig('covariance_heatmap.png', dpi=300, bbox_inches='tight')
print("\n✓ Covariance heatmap saved as 'covariance_heatmap.png'")

# ============================================================================
# 7. MULTIVARIATE ANALYSIS
# ============================================================================
print("\n" + "="*80)
print("[7] MULTIVARIATE ANALYSIS")
print("="*80)

# Pair plot for top 5 correlated features
top_5_features = correlations.abs().sort_values(ascending=False).head(5).index.tolist()
print(f"\nCreating pair plot for top 5 features: {top_5_features}")

pairplot_df = df[top_5_features + ['quality_binary']]
sns.pairplot(pairplot_df, hue='quality_binary', palette='Set1',
             diag_kind='kde', plot_kws={'alpha': 0.6})
plt.savefig('pairplot_multivariate.png', dpi=300, bbox_inches='tight')
print("✓ Pair plot saved as 'pairplot_multivariate.png'")

# 3D scatter plot
from mpl_toolkits.mplot3d import Axes3D

fig = plt.figure(figsize=(12, 8))
ax = fig.add_subplot(111, projection='3d')

colors = ['red' if x == 0 else 'green' for x in df['quality_binary']]
ax.scatter(df[top_5_features[0]], df[top_5_features[1]],
           df[top_5_features[2]], c=colors, alpha=0.5)

ax.set_xlabel(top_5_features[0])
ax.set_ylabel(top_5_features[1])
ax.set_zlabel(top_5_features[2])
ax.set_title('3D Scatter Plot of Top Features')
plt.savefig('3d_scatter.png', dpi=300, bbox_inches='tight')
print("✓ 3D scatter plot saved as '3d_scatter.png'")

# ============================================================================
# 8. OUTLIER DETECTION AND REMOVAL
# ============================================================================
print("\n" + "="*80)
print("[8] OUTLIER DETECTION AND REMOVAL")
print("="*80)

print(f"\nOriginal dataset size: {df.shape[0]} rows")

# Detect outliers using IQR method
def detect_outliers_iqr(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return (df[column] < lower_bound) | (df[column] > upper_bound)

# Count outliers per feature
outlier_counts = {}
for col in numerical_features:
    outliers = detect_outliers_iqr(df, col)
    outlier_counts[col] = outliers.sum()

print("\nOutlier counts by feature:")
for feature, count in sorted(outlier_counts.items(), key=lambda x: x[1], reverse=True):
    print(f"{feature}: {count} outliers ({count/len(df)*100:.2f}%)")

# Remove rows with outliers in any feature
df_no_outliers = df.copy()
for col in numerical_features:
    outliers = detect_outliers_iqr(df_no_outliers, col)
    df_no_outliers = df_no_outliers[~outliers]

print(f"\nDataset size after outlier removal: {df_no_outliers.shape[0]} rows")
print(f"Removed {df.shape[0] - df_no_outliers.shape[0]} rows ({(df.shape[0] - df_no_outliers.shape[0])/df.shape[0]*100:.2f}%)")

# Visualize before and after
fig, axes = plt.subplots(2, 2, figsize=(14, 10))
axes = axes.ravel()

for idx, feature in enumerate(top_features):
    axes[idx].boxplot([df[feature], df_no_outliers[feature]],
                       labels=['With Outliers', 'Without Outliers'])
    axes[idx].set_title(f'Outlier Removal: {feature}')
    axes[idx].set_ylabel(feature)

plt.tight_layout()
plt.savefig('outlier_removal.png', dpi=300, bbox_inches='tight')
print("\n✓ Outlier removal comparison saved as 'outlier_removal.png'")

# ============================================================================
# 9. LOGISTIC REGRESSION CLASSIFICATION
# ============================================================================
print("\n" + "="*80)
print("[9] LOGISTIC REGRESSION CLASSIFICATION")
print("="*80)

# Prepare data
X = df_no_outliers[numerical_features]
y = df_no_outliers['quality_binary']

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,
                                                      random_state=42, stratify=y)

print(f"\nTraining set size: {X_train.shape[0]}")
print(f"Test set size: {X_test.shape[0]}")
print(f"\nClass distribution in training set:")
print(y_train.value_counts(normalize=True))

# Standardize features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train Logistic Regression
print("\nTraining Logistic Regression model...")
log_reg = LogisticRegression(random_state=42, max_iter=1000)
log_reg.fit(X_train_scaled, y_train)

# Predictions
y_pred = log_reg.predict(X_test_scaled)
y_pred_proba = log_reg.predict_proba(X_test_scaled)[:, 1]

# ============================================================================
# 10. MODEL EVALUATION
# ============================================================================
print("\n" + "="*80)
print("[10] MODEL EVALUATION")
print("="*80)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"\nAccuracy: {accuracy:.4f} ({accuracy*100:.2f}%)")

# Classification Report
print("\nClassification Report:")
print(classification_report(y_test, y_pred,
                          target_names=['Poor Wine (0)', 'Good Wine (1)']))

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:")
print(cm)

# Visualize Confusion Matrix
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Poor (0)', 'Good (1)'],
            yticklabels=['Poor (0)', 'Good (1)'])
plt.title('Confusion Matrix')
plt.ylabel('Actual')
plt.xlabel('Predicted')
plt.savefig('confusion_matrix.png', dpi=300, bbox_inches='tight')
print("\n✓ Confusion matrix saved as 'confusion_matrix.png'")

# ROC Curve
fpr, tpr, thresholds = roc_curve(y_test, y_pred_proba)
roc_auc = roc_auc_score(y_test, y_pred_proba)

plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, color='darkorange', lw=2,
         label=f'ROC curve (AUC = {roc_auc:.2f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--', label='Random Classifier')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve')
plt.legend(loc="lower right")
plt.grid(alpha=0.3)
plt.savefig('roc_curve.png', dpi=300, bbox_inches='tight')
print(f"✓ ROC curve saved as 'roc_curve.png'")
print(f"\nROC AUC Score: {roc_auc:.4f}")

# Feature Importance
feature_importance = pd.DataFrame({
    'Feature': numerical_features,
    'Coefficient': log_reg.coef_[0]
}).sort_values('Coefficient', ascending=False)

print("\nFeature Importance (Coefficients):")
print(feature_importance)

plt.figure(figsize=(10, 6))
plt.barh(feature_importance['Feature'], feature_importance['Coefficient'])
plt.xlabel('Coefficient Value')
plt.title('Feature Importance in Logistic Regression')
plt.tight_layout()
plt.savefig('feature_importance.png', dpi=300, bbox_inches='tight')
print("\n✓ Feature importance plot saved as 'feature_importance.png'")